Works section(mobile)
nstrvs/portfolio pull request #2
Opened 2022-01-06 20:45 UTC by nstrvs

This brunch contains two new sections in the mobile version: works, and about me.

2022-01-07 23:29 UTC, Whoistolu requested changes
Hi @nstrvs ,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ] [REQUIRED] It will be nice to have a descriptive Pull Request that is also free of spelling errors (e.g use branch instead of brunch). This is in accordance with professional practice. 

### See your PR Description
![PR](https://user-images.githubusercontent.com/58692590/148619547-19b6b209-a535-4b79-a05a-4928b4c94769.png)

### Microverse Descriptive PR [Template](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md)


- [ ] [REQUIRED] Kindly stick to the provided [figma template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=23%3A9) as much as possible.
You need to make your project section fit the width of the mobile version. You seem to have some margin on the right side of your design. See below:

### Your design
![your-design](https://user-images.githubusercontent.com/58692590/148618023-cadd473d-6c72-435d-b642-2d0f30110370.png)

### Figma
![figma3](https://user-images.githubusercontent.com/58692590/148618072-b912199f-e9c1-4a38-b2a7-8b2a25cfc152.png)

_Check the inline comments under the review for sections to improve._

### Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Note that the list of project technologies is a list `ul` and each of them a `li`. Please ensure to put this list in an unordered list `ul` and each of the technology in a `li` tag. This makes your code more correct and helps screen readers and other technologies that depend on correct semantics to work.

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Please refer to my previous comment about embedding the list of technologies in a `ul` and `li` tag.

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Please refer to my previous comment about embedding the list of technologies in a `ul` and `li` tag.

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Please refer to my previous comment about embedding the list of technologies in a `ul` and `li` tag.

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Please refer to my previous comment about embedding the list of technologies in a `ul` and `li` tag.

2022-01-07 23:29 UTC, Whoistolu commented on index.html
> +            </div>
- [ ] [REQUIRED] Please refer to my previous comment about embedding the list of technologies in a `ul` and `li` tag.

2022-01-07 23:43 UTC, nstrvs commented
Hey @Whoistolu thanks for the review, I have already changed the description of the branch. 

Regarding the another request, the Figma template is 320px width, I designed my website in that size, so if you review it like that, it'll fit perfectly.

2022-01-08 00:08 UTC, Lordkaito approved these changes
Hi @nstrvs, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 00:36 UTC, merged

2022-01-08 07:33 UTC, Whoistolu commented
> Hey @Whoistolu thanks for the review, I have already changed the description of the branch.
> 
> Regarding the another request, the Figma template is 320px width, I designed my website in that size, so if you review it like that, it'll fit perfectly.

###Great job @nstrvs 
Happy coding!