Contact form mobile version
nstrvs/portfolio pull request #3
Opened 2022-01-11 21:58 UTC by nstrvs

### Description of branch
-  [ ] Create form 
-  [ ] Link form to Formspree

2022-01-11 23:50 UTC, Amrhub requested changes
Hi @nstrvs @41hulk,  👋🏻 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!
These changes aim to add some awesomeness to your awesome project and code skills.

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-11 23:50 UTC, Amrhub commented on index.html
> +    </section>
- [ ] You implemented functionality perfectly fine, but we need to work on our styling to match The Figma design 

Your Implementation | [Figma Design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=67%3A1095)
:----:|:-----:
![image](https://user-images.githubusercontent.com/87689547/149039103-6b1eb3d1-f6f7-4695-8e2d-6a9bfe027950.png) | ![image](https://user-images.githubusercontent.com/87689547/149039140-62d9deae-de8a-4bd7-bc4a-61243afd9792.png)

Please let me know if you have any troubles made you not implement that at all.

2022-01-11 23:59 UTC, nstrvs commented
Thanks for your suggestion @Amrhub, but I used media queries of 320px width (accordingly to the figma design), that's why you didn't see any design. 

Please check that before giving a review.

2022-01-12 00:11 UTC, mke2111 commented
Project Under Second Opinion Review.
Kindly wait for a response to come your way. 🙏🏽

2022-01-12 00:29 UTC, mke2111 reviewed
Hello  @nstrvs & @41hulk 👋,

_This is an additional review as a result of the second opinion request._

Your project is taking shape and looks great based on what you have done so far. 👍🏽 Keep going 😉 

For mobile-first approach, think of these mobile screen sizes ranging from 300px - 516px/768px. So you're limiting your styles to apply to only the screen sizes that are 320px and below and it's the reason the styles break(don't apply) once the width is above 320px. What you want is a max-width of 768px and below.

Make the requested change to cater to all mobile screen sizes using a max-width of 768px. Submit another code review request (CRR) once you are ready and somebody will give a review.

Keep rocking 🚀 and Happy Coding 💻

2022-01-12 17:33 UTC, Deepakdanger approved these changes
Hi @nstrvs, 

### Status: Approved ✔️

Well Done implementing on the suggested changes. Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-12 17:54 UTC, merged